### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by edent** [optimalprimate/optimalprimate.github.io#1]
Great write up!

There's a missing image at https://github.com/optimalprimate/optimalprimate.github.io/raw/master/images/frame_comp.jpg - I think it should be `mm_frame_comp.jpg`

The gif doesn't render in `<details>` HTML on the main site. Although it does if I view it through GitHub's interface. I don't think you can put markdown inside HTML in that way.

What a fun project!

**Comment by optimalprimate** [comment]
Thank you for that! Fixed the image link.
Plus, you're totally right, you can't put markdown inside HTML, so used HTML for the gif ref and seems to work now!

Thanks again, still getting my head around hosting a blog on github...
